trigger:
- testing

pool:
  vmImage: windows-2022
workspace:
      clean: all

steps:
- task: DownloadSecureFile@1
  name: FetchSSHKey
  inputs:
    secureFile: 'id_rsa'  # The name of your SSH private key file

- script: |
    mkdir -p ~/.ssh
    cp $(FetchSSHKey.secureFilePath) ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan github.com >> ~/.ssh/known_hosts  # Add GitHub to known hosts
  displayName: Setup SSH Key for GitHub

# Step to install Python package from GitHub
- script: |
    python -m pip install --upgrade pip    
    python -m pip install git+https://$(GITHUB_USER):$(GITHUB_PAT)@github.com/$(GITHUB_USER)/gci-cli.git@develop
  displayName: Install gci-cli from Private GitHub Repository (Develop Branch)
- script:  |
    gci version
    gci-cli version
  displayName: Test version of gci