# Sadly the max limit for a build is 60 minutes for pipeline.
# With the new features the build exceeds, due two a slow 2 core machine.

trigger:
- master

pool:
  vmImage: windows-2022
workspace:
      clean: all

