trigger:
- testing

pool:
  vmImage: windows-2022
workspace:
      clean: all

steps:
# Step to install Python package from GitHub
- script: |
    python -m pip install --upgrade pip
    python -m pip install git+https://github.com/thommyho/gci-cli.git
  displayName: Install gci-cli from GitHub